Re-export, `TicketFuture` complete, and Documentation
BrunoJurkovic/flip_card pull request #85
Opened 2023-06-03 18:18 UTC by m-haisham

# Description

Three (minor) changes:
- Refactor and re-export so that we don't have to import `package:flip_card/flip_card_controller.dart`.
- Make sure `TickerFuture` await completion whether cancelled or not in flip and skew.
- Improvement documentation by adding doc-strings to missing classes

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] Self-Code Review
- [x] Tested on example project

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] Changed the example project to contain the new feature (only if applies)

2023-06-03 20:18 UTC, ciriousjoker requested changes
Minor typo maybe, aside from that it looks good. Kind of unfortunate that git doesn't pick up on the file relocation and everything shows up as a change, but what can you do.

2023-06-03 20:18 UTC, ciriousjoker commented on lib/src/flip_card_transition.dart
> +/// at the cost of built it methods like [FlipCardState.flip]
typo? built-in

2023-06-04 01:50 UTC, m-haisham commented on lib/src/flip_card_transition.dart
> +/// at the cost of built it methods like [FlipCardState.flip]
Ah yes, Nice catch. Thanks

2023-06-23 15:44 UTC, ciriousjoker approved these changes
lgtm, sorry I missed your commit

2023-07-04 21:50 UTC, ciriousjoker commented
@BrunoJurkovic you can build a new version

2023-07-04 21:50 UTC, merged